services:
  zabbix-agent:
    build:
      dockerfile_inline: |
        FROM zabbix/zabbix-agent:alpine-latest
        USER root
        RUN apk add --no-cache python3 py3-pip git jq && pip3 install --break-system-packages git+https://github.com/truenas/api_client.git
        USER zabbix
    configs:
      - source: conf/truenas.conf
        target: /etc/zabbix/zabbix_agentd.d/truenas.conf
    environment:
      TRUENAS_KEY: # Your TrueNAS API key
      TRUENAS_URL: wss://YOUR.TRUENAS.SERVER/websocket
      TZ: # Your timezone, e.g., 'Australia/Sydney'
      ZBX_PASSIVESERVERS: '::/0'
      ZBX_SERVER_HOST: # Your Zabbix server hostname or IP
      ZBX_TIMEOUT: 10
    group_add:
      - 568
    hostname: truenas-zabbix-agent
    image: lingfish/truenas-zabbix-agent
    platform: linux/amd64
    ports:
      - '10050:10050'
    privileged: False
    pull_policy: missing
    restart: 'no'
    stdin_open: False
    tty: False
